esphome:
  name: "buzz-lightyear"
  platform: ESP8266
  board: huzzah

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

status_led:
  pin: 
    number: GPIO2
    inverted: True

api:

logger:

ota:

sensor:
  - platform: wifi_signal
    name: "Buzz Lightyear WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Buzz Uptime"
    update_interval: 60s

light:
  - platform: neopixelbus
    id: buzz
    restore_mode: ALWAYS_ON
    type: GRB
    variant: ws2812x
    pin: GPIO12
    num_leds: 11
    name: "NeoPixel Light"
    effects:
      - addressable_lambda:
          name: "buzz scan"
          update_interval: 200ms
          lambda: |-
            static uint16_t progress = 0;
            it.all() = Color::BLACK;
            
            switch(progress) {
              case 0:
                break;
              case 1 ... 5:
                for (int i = 0; i < 5; i++) {
                  if (i > 5 - progress - 1) {
                    it[i] = Color(0, 175, 0);
                  }
                }
                for (int i = 5; i < 10; i++) {
                  if (i <= progress + 5 - 1) {
                    it[i] = Color(175, 0, 0);
                  }
                }
              case 6:
                break;
              case 7:
                for (int i = 0; i < 5; i++) {
                  it[i] = Color(0, 175, 0);
                }
                for (int i = 5; i < 10; i++) {
                  it[i] = Color(175, 0, 0);
                }
              case 8:
                break;
              case 9:
                for (int i = 0; i < 5; i++) {
                  it[i] = Color(0, 175, 0);
                }
                for (int i = 5; i < 10; i++) {
                  it[i] = Color(175, 0, 0);
                }
            }
            
            if (progress % 2 == 0) {
              it[10] = Color(255, 0, 0);
            }
            
            progress++;
            if (progress == 10) {
              progress = 0;
            }
    on_turn_on:
      - light.turn_on: 
          id: buzz
          effect: "buzz scan"