esphome:
  name: magic_lamp
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

status_led:
  pin: 
    number: GPIO2
    inverted: False

api:

logger:

ota:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO12
    num_leds: 60
    rgb_order: GRB
    max_refresh_rate: 10ms
    name: "Magic Lamp"
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_random_twinkle:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_fireworks: