esphome:
  name: temperature_sensor
  platform: ESP8266
  board: huzzah
  includes:
    - mcp9808_sensor.h
  libraries:
    - "SPI"
    - "Wire"
    - "Adafruit Unified Sensor"
    - "Adafruit BusIO"
    - "Adafruit MCP9808 Library"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

status_led:
  pin: 
    number: GPIO2
    inverted: True

api:

logger:

ota:

sensor:
  - platform: wifi_signal
    name: "Temperature Sensor WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Temperature Sensor Uptime"
    update_interval: 60s

  - platform: custom
    lambda: |-
      auto my_sensor = new Mcp9808Sensor();
      App.register_component(my_sensor);
      return {my_sensor};
  
    sensors:
      name: "Temperature Sensor"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      accuracy_decimals: 2

i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a